language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "6"


  # safelist
branches:
  only:
  - master


script:
 - npm -v

install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --token $FIREBASE_TOKEN